import 'package:get/get.dart';

class AppLocalization extends Translations{
  @override
  Map<String, Map<String, String>> get keys =>{

    'ar_SA':{
      "Calls":"المكالمات",
      "Messages":"رسائل",
      "Contact":"اتصل",
      "User_Info":"معلومات المستخدم",
      "Skip":"يتخطى",
      "Submit":"إرسال",
      "Register":"يسجل",
      "Send_Location":"إرسال موقع",
      "Normal":"طبيعي",
      "Hybrid":"هجين",
      "Satellite":"الأقمار الصناعية",
      "Terrain":"تضاريس",
      "Done":"فعله",
      "Registration":"تسجيل",
      "One_Time":"سنرسل لك كلمة مرور لمرة واحدة على هذا الرقم",
      "Generate_OTP":"توليد OTP",
      "Media":"وسائط",
      "Photos":"الصور",
      "Videos":"أشرطة فيديو",
      "Files":"الملفات",
      "Reply":"رد",
      "Copy":"ينسخ",
      "Delete":"حذف",
      "Record_New_Video":"تسجيل فيديو جديد",
      "Gallery":"صالة عرض",
      "Swipe_to_delete":"انتقد للحذف",
      "Profile":"الملف الشخصي",
      "Username":"اسم المستخدم",
      "Status":"حالة",
      "Number":"عدد",
      "View_&_edit_profile":"عرض وتحرير الملف الشخصي",
      "Language":"لغة التطبيق",
      "Help":"يساعد",
      "About":"عن",
      "Logout":"تسجيل خروج",
      "Flutter_Chat_App":"تطبيق Flutter Chat",
      "Starred_Messages":"الرسائل المميزة بنجمة",
      "Type_a_status":"اكتب حالة",
      "Media_Links_&_Docs":"الوسائط والروابط والمستندات",
      "OTP_Verification":"التحقق من OTP",
      "Verify_OTP":"تحقق من OTP",
      "Agora_Video_Call":"أجورا فيديو كول",
      "Cropper_Image":"صورة كروبر",
      "Outgoing":"منفتح",
      "Incoming":"واردة",
      "Missed":"افتقد",
    },

    'en_US':{
      "Calls":"Calls",
      "Messages":"Messages",
      "Contact":"Contact",
      "User_Info":"User Info",
      "Skip":"Skip",
      "Submit":"Submit",
      "Register":"Register",
      "Send_Location":"Send Location",
      "Normal":"Normal",
      "Hybrid":"Hybrid",
      "Satellite":"Satellite",
      "Terrain":"Terrain",
      "Done":"Done",
      "Registration":"Registration",
      "One_Time":"We will send you one time password on this number",
      "Generate_OTP":"Generate OTP",
      "Media":"Media",
      "Photos":"Photos",
      "Videos":"Videos",
      "Files":"Files",
      "Reply":"Reply",
      "Copy":"Copy",
      "Delete":"Delete",
      "Record_New_Video":"Record New Video",
      "Gallery":"Gallery",
      "Swipe_to_delete":"Swipe to delete",
      "Profile":"Profile",
      "Username":"Username",
      "Status":"Status",
      "Number":"Number",
      "View_&_edit_profile":"View & edit profile",
      "Language":"App Language",
      "Help":"Help",
      "About":"About",
      "Logout":"Logout",
      "Flutter_Chat_App":"Flutter Chat App",
      "Starred_Messages":"Starred Messages",
      "Type_a_status":"Type a status",
      "Media_Links_&_Docs":"Media, Links & Docs",
      "OTP_Verification":"OTP Verification",
      "Verify_OTP":"Verify OTP",
      "Agora_Video_Call":"Agora Video Call",
      "Cropper_Image":"Cropper Image",
      "Outgoing":"Outgoing",
      "Incoming":"Incoming",
      "Missed":"Missed",
    },

    'es_US':{
      "Calls":"Llamadas",
      "Messages":"Mensajes",
      "Contact":"Contacto",
      "User_Info":"Información de usuario",
      "Skip":"Saltar",
      "Submit":"Entregar",
      "Register":"Registrarse",
      "Send_Location":"Enviar ubicación",
      "Normal":"Normal",
      "Hybrid":"Híbrida",
      "Satellite":"Satélite",
      "Terrain":"Terreno",
      "Done":"Hecho",
      "Registration":"Registro",
      "One_Time":"Le enviaremos una contraseña de un solo uso en este número",
      "Generate_OTP":"Generar OTP",
      "Media":"Medios de comunicación",
      "Photos":"Fotos",
      "Videos":"Vídeos",
      "Files":"archivos",
      "Reply":"Respuesta",
      "Copy":"Dupdo",
      "Delete":"Borrar",
      "Record_New_Video":"Grabar nuevo video",
      "Gallery":"Galería",
      "Swipe_to_delete":"Deslizar para eliminar",
      "Profile":"Perfil",
      "Username":"Nombre de usuario",
      "Status":"Estado",
      "Number":"Número",
      "View_&_edit_profile":"Ver y editar perfil",
      "Language":"Idioma de la aplicación",
      "Help":"Ayudar",
      "About":"Acerca de",
      "Logout":"Cerrar sesión",
      "Flutter_Chat_App":"Aplicación de chat Flutter",
      "Starred_Messages":"Mensajes destacados",
      "Type_a_status":"Escriba un estado",
      "Media_Links_&_Docs":"Medios, enlaces y documentos",
      "OTP_Verification":"Verificación OTP",
      "Verify_OTP":"Verificar OTP",
      "Agora_Video_Call":"Videollamada de Ágora",
      "Cropper_Image":"Imagen recortadora",
      "Outgoing":"Saliente",
      "Incoming":"Entrante",
      "Missed":"Omitido",
    },

    'ur_PK':{
      "Calls":"کالز",
      "Messages":"پیغامات",
      "Contact":"رابطہ کریں",
      "User_Info":"صارف کی معلومات",
      "Skip":"چھوڑ دو",
      "Submit":"جمع کرائیں",
      "Register":"رجسٹر کریں",
      "Send_Location":"مقام بھیجیں",
      "Normal":"نارمل",
      "Hybrid":"ہائبرڈ",
      "Satellite":"سیٹلائٹ",
      "Terrain":"خطہ",
      "Done":"ہو گیا",
      "Registration":"اندراج",
      "One_Time":"ہم آپ کو اس نمبر پر ون ٹائم پاس ورڈ بھیجیں گے",
      "Generate_OTP":"OTP بنائیں",
      "Media":"میڈیا",
      "Photos":"تصاویر",
      "Videos":"ویڈیوز",
      "Files":"فائلوں",
      "Reply":"جواب دیں",
      "Copy":"کاپی کریں",
      "Delete":"حذف کریں",
      "Record_New_Video":"نئی ویڈیو ریکارڈ کریں",
      "Gallery":"Gallery",
      "Swipe_to_delete":"حذف کرنے کے لیے سوائپ کریں",
      "Profile":"پروفائل",
      "Username":"صارف نام",
      "Status":"حالت",
      "Number":"نمبر",
      "View_&_edit_profile":"پروفائل دیکھیں اور ترمیم کریں",
      "Language":"ایپ کی زبان",
      "Help":"مدد",
      "About":"کے بارے میں",
      "Logout":"لاگ آوٹ",
      "Flutter_Chat_App":"فلٹر چیٹ ایپ",
      "Starred_Messages":"ستارے والے پیغامات",
      "Type_a_status":"اسٹیٹس ٹائپ کریں",
      "Media_Links_&_Docs":"میڈیا، لنکس اور دستاویزات",
      "OTP_Verification":"OTP کی تصدیق",
      "Verify_OTP":"OTP کی تصدیق کریں",
      "Agora_Video_Call":"اگورا ویڈیو کال",
      "Cropper_Image":"کرپر امیج",
      "Outgoing":"سبکدوش ہونے والے",
      "Incoming":"آنے والا",
      "Missed":"چھوٹ گیا",
    },

  };

}